### PR TITLE
Add support for dynamic snapshot URL

### PR DESCRIPTION
**Pull request by maksbotan**
This change lets user specify that certain snapshot URL must be always
re-fetched when it's not present in the lock file by appending "?"
symbol to the URL.

---

At our company (@biocad) we are maintaining our own Stack's custom snapshot with our private packages. To avoid updating all packages' `stack.yaml` files on each update of the snapshot (which happen rather often, but does not affect all the project at once), we keep it at the same URL, asking Stack to re-fetch it when it changes.

Right now, there are two ways to do so:

- Clear whole Pantry database by removing `~/.stack/pantry/pantry.sqlite3` file. This, of course, results in re-fetching and re-indexing of the whole Hackage snapshot, taking a lot of time. This already costs an uncomfortable delay in our CI jobs.
- Fiddle with `sqlite3` to remove only our snapshot from `blob` and `url_blob` Pantry tables, to force Stack to re-fetch only really changed parts.

Second way is fast, but is too implementation-dependent.

I would like to propose a cleaner solution to our problem, that might help other Stack users out there.

Let's allow users to add a certain marker (I chose "`?`", since it's a valid _and_ harmless symbol in URL, moreover it's often used to mark dynamic, not-to-be-cached URLs) to specify that snapshot URL must be refetched when it's not found in the lock file, bypassing Pantry cache altogether.

I would like to hear your thoughts on this or maybe on alternative ways to solve our problem.

---

Right now this results in duplicated entries for the same snapshot URL in the `url_blob` table:

```
14|http://127.0.0.1:8000/lts-test.yaml?|140901|2020-02-08T21:36:10.170825
15|http://127.0.0.1:8000/lts-test.yaml?|140902|2020-02-08T21:37:02.573998
```

If that's a problem, I could update Pantry code to re-write table entry when an URL gets re-fetched. Or maybe to skip saving such blobs to Pantry at all, which would also solve the problem.

---

If you agree to this change, I will propose an update in Stack's documentation as well.

---

Thanks. Looking forward to the response.

### CODE REVIEW

**Comment by snoyberg** [comment]
I'd rather not add changes that encourage a non-reproducible workflow. My recommendation for your use case would be to create versioned snapshot files at different URLs. But to match your current workflow with current Stack, what about including an incrementing query string parameter in your stack.yaml file? That should force Stack to redownload each time you increment, and avoid any confusion of your pantry database having multiple entries for the same URL.

**Comment by maksbotan** [comment]
Of course, adding incrementing query parameter would solve the problem in the sense of forcing Stack to re-fetch the snapshot.

However, it doesn't quite match our workflow, since we wouldn't like to touch our `stack.yaml` files on each snapshot update. Dropping `stack.yaml.lock` to trigger re-fetch seems as a far more simple solution. Moreover, it's easily automated in CI.

If you don't agree to add support for non-deterministic URLs, how about making an official way to drop some URLs from cache with stack command, without resorting to raw `sqlite3` commands?

**Comment by snoyberg** [comment]
I'm not really in favor of _any_ changes that encourage a non-deterministic workflow. The entirety of Pantry is designed around deterministic build plans, and the workflow you're describing explicitly goes against this. I would strongly encourage going in a different direction.

**Comment by snoyberg** [comment]
Closing as wontfix

**Pull request closed without merging**
