### PR TITLE
Remove operational and mirror keys from bootstrap key set

### PR DESCRIPTION
**Pull request by david-christiansen**
The list of keys passed to the Hackage Security setup should be the
bootstrap root keys, rather than all keys used.

There are three kinds of keys used with Hackage Security today:

 * root keys, which are the community roots of trust, kept offline and
   distributed among trusted community members,

 * operational keys, which are kept in memory on Hackage and used for
   ongoing cryptographic signatures of the timestamp file and index,

 * and mirror keys, which are used to sign the mirror list.

Tools that wish to interact with Hackage need to carry a bootstrap set
of root keys to solve the chicked-and-egg problem. These are five root
keys that are implicitly trusted. These keys are used to sign
root.json in Hackage, which then specifies which additional keys are
available and used. The list here, however, contains all the keys,
rather than just the bootstrap root keys.

### CODE REVIEW

**Comment by david-christiansen** [comment]
The keys seem to be used here: https://github.com/commercialhaskell/pantry/blob/7330161506ab821fefefa965333918fe75091af1/src/Pantry/Hackage.hs#L151-L154

which is using them for bootstrap. Cf https://github.com/haskell/cabal/blob/c024065b2104fab366ea14775ca4191764d382bd/cabal-install/src/Distribution/Client/Config.hs#L683-L690 for the corresponding bit in `cabal-install`.

For more context, please see my [README PR to `hackage-security`](https://github.com/haskell/hackage-security/pull/279).

**Comment by david-christiansen** [comment]
I rebuilt Stack using this version, set `STACK_ROOT` to a fresh temporary directory, and asked this stack to build itself. It seemed to do the right thing, so I think that this patch works.

**Review by snoyberg — APPROVED** [review]
Thanks!

**Comment by snoyberg** [comment]
I've released pantry 0.5.6 to Hackage and opened a matching Stack PR: https://github.com/commercialhaskell/stack/pull/5785

**Pull request merged**
