### PR TITLE
Support basic auth

### PR DESCRIPTION
**Pull request by brandon-leapyear**
Fixes https://github.com/commercialhaskell/stack/issues/5509

Tested that it works with our private hackage instance

### CODE REVIEW

**Comment by snoyberg** [comment]
I'm not on board with this approach, it's too easy to accidentally ignore the subtle differences between the local and upstream versions of the function. How about modifying `HttpClient.hs` to call more appropriate API functions? Honestly, even after reading the Stack issue and this PR, I'm not certain what exact bug you're trying to fix.

**Comment by brandon-leapyear** [comment]
Sure, I can make a completely separate function instead of shadowing the
function in Pantry.HTTP.

The problem we're trying to solve is using a private hackage instance that
requires authentication. So trying to do

```yaml
package-indices:
- download-prefix: ***@***.***
```

Will fail to pass the username and password through

**Comment by brandon-leapyear** [comment]
Done!

**Review by snoyberg — APPROVED** [review]
Thanks!

**Pull request merged**
