### PR TITLE
Expand cabal bounds

### LINKED ISSUE #37: Support Cabal 3.4.0.0
Cabal released 3.4.0.0 in February. It would be great to expand these bounds. There shouldn't need to be any code changes; I built pantry fine with Cabal 3.4.0.0 locally.

### PR DESCRIPTION
**Pull request by brandon-leapyear**
Resolves #37

### CODE REVIEW

**Comment by snoyberg** [comment]
It would be ideal to include a new build in the test matrix that checks this version. I can add that to this PR some time next week, or provide guidance if you're interested in taking a stab at doing so.

**Comment by brandon-leapyear** [comment]
If it's not too difficult I can do it. It seems like it's just a matter of adding a new `stack.yaml` file and adding it to each other templates in `.azure/`?

**Comment by snoyberg** [comment]
Basically yes

**Comment by snoyberg** [comment]
Looks perfect, thanks!

**Pull request merged**
