### PR TITLE
Add `forceLocal` to Bsd archiveSubmodules command

### PR DESCRIPTION
**Pull request by spacekitteh**
To fix https://github.com/commercialhaskell/stack/issues/5135

### CODE REVIEW

**Comment by psibi** [comment]
@spacekitteh Thanks for the MR! But I think this wouldn't work because IIRC the BSD's tar doesn't support the `--force-local` option: https://www.freebsd.org/cgi/man.cgi?query=bsdtar&sektion=1&manpath=freebsd-release-ports

Did you check if the PR fixes the bug reported by you ?

**Comment by snoyberg** [comment]
@spacekitteh bump

**Comment by mpilgrem** [comment]
On Windows 11, `where.exe tar` or `stack exec -- where.exe tar` is `C:\Windows\System32\tar.exe` and `tar --version` is `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp bz2lib/1.0.6`. That executable does not support a `--force-local` option. However, GNU tar 1.34 can be added to the Stack-supplied MSYS2 with `stack exec -- pacman -S tar`.

**Comment by mpilgrem** [comment]
Closing, as now fixed by #84.

**Pull request closed without merging**
